@extends('layouts.app')
@section('title','Service')
@section('content')
<div class="space-y-5"><div class="flex justify-between"><div><a class="text-sm text-primary" href="{{ route('web.services.index') }}">← Services</a><h1 class="mt-2 text-2xl font-bold">{{ $service->name }}</h1><p class="text-gray-500">{{ $service->department?->name }}</p></div>@can('update', $service)<a class="inline-flex h-10 items-center rounded bg-primary px-4 text-sm text-white" href="{{ route('web.services.edit',$service) }}">Edit</a>@endcan</div><div class="rounded-lg border bg-background p-5 shadow-sm"><dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Type</dt><dd>{{ $service->type }}</dd></div><div><dt class="text-gray-500">Duration</dt><dd>{{ $service->duration }}</dd></div><div><dt class="text-gray-500">Price</dt><dd>{{ number_format((float)$service->price,2) }} {{ $service->currency }}</dd></div><div><dt class="text-gray-500">Status</dt><dd>{{ $service->status }}</dd></div></dl>
@can('delete', $service)
    @if ($service->status === 'Active')
        <form class="mt-6" method="POST" action="{{ route('web.services.destroy',$service) }}" onsubmit="return confirm('Deactivate this service?');">@csrf @method('DELETE')<button class="text-sm text-red-600">Deactivate service</button></form>
    @endif
@endcan
</div><div class="rounded-lg border bg-background p-5 shadow-sm"><h2 class="text-lg font-semibold">Availability</h2><form class="mt-4 flex flex-col gap-2 sm:flex-row" method="POST" action="{{ route('web.services.availability.store',$service) }}">@csrf<select name="day_of_week" class="h-10 rounded-md border px-3" required><option value="">Day</option>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as $day)<option value="{{ $day }}">{{ $day }}</option>@endforeach</select><input name="slots" placeholder="09:00-13:00, 14:00-17:00" class="h-10 flex-1 rounded-md border px-3" required>@can('update',$service)<button class="rounded-md bg-primary px-4 py-2 text-sm text-white">Save</button>@endcan</form><div class="mt-4 space-y-2">@forelse($service->availability as $slot)<div class="flex items-center justify-between rounded border p-3 text-sm"><span><strong>{{ $slot->day_of_week }}</strong> · {{ $slot->slots }}</span>@can('update',$service)<form method="POST" action="{{ route('web.services.availability.destroy',[$service,$slot]) }}">@csrf @method('DELETE')<button class="text-red-600">Remove</button></form>@endcan</div>@empty<p class="text-sm text-gray-500">No availability configured.</p>@endforelse</div></div></div>
@endsection
