@extends('layouts.app')
@section('title', 'Staff Profile')
@section('content')
<div class="flex flex-col gap-5">
    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><a href="{{ route('web.staff.index') }}" class="text-sm text-primary">← Care team</a><h1 class="mt-2 text-2xl font-bold lg:text-3xl">{{ $staff->full_name }}</h1><p class="text-gray-500">{{ $staff->code }} · {{ $staff->role }}</p></div>@can('update', $staff)<div class="flex gap-2"><a href="{{ route('web.staff.hr.show', $staff) }}" class="inline-flex h-10 items-center rounded-md border px-4 text-sm">HR records</a><a href="{{ route('web.staff.edit', $staff) }}" class="inline-flex h-10 items-center rounded-md bg-primary px-4 text-sm text-white">Edit staff member</a></div>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-3">
        <section class="rounded-lg border bg-background p-5 shadow-sm lg:col-span-2"><h2 class="mb-4 text-xl font-semibold">Employment details</h2><dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Role and position</dt><dd class="mt-1 font-medium">{{ $staff->role }}{{ $staff->position ? ' · '.$staff->position : '' }}</dd></div><div><dt class="text-gray-500">Department</dt><dd class="mt-1 font-medium">{{ $staff->department?->name ?? 'Unassigned' }}</dd></div><div><dt class="text-gray-500">Email</dt><dd class="mt-1 font-medium">{{ $staff->email }}</dd></div><div><dt class="text-gray-500">Phone</dt><dd class="mt-1 font-medium">{{ $staff->phone ?: '—' }}</dd></div><div><dt class="text-gray-500">Joined</dt><dd class="mt-1 font-medium">{{ $staff->joined_date?->format('d M Y') ?? '—' }}</dd></div><div><dt class="text-gray-500">Status</dt><dd class="mt-1 font-medium">{{ $staff->status }}</dd></div></dl></section>
        <aside class="rounded-lg border bg-background p-5 shadow-sm"><h2 class="text-xl font-semibold">Login access</h2>@if($staff->user->isNotEmpty())<p class="mt-3 text-sm font-medium">{{ $staff->user->first()->email }}</p><p class="text-sm text-gray-500">Role: {{ $staff->user->first()->role_label }}</p>@else<p class="mt-3 text-sm text-gray-500">No login account is linked.</p>@endif @can('delete', $staff)@if($staff->status !== 'Inactive')<form method="POST" action="{{ route('web.staff.destroy', $staff) }}" class="mt-6" onsubmit="return confirm('Deactivate this staff member and their login access?');">@csrf @method('DELETE')<button class="text-sm text-red-600">Deactivate staff member</button></form>@endif @endcan</aside>
    </div>
    <section class="rounded-lg border bg-background p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-xl font-semibold">Certifications</h2><p class="text-sm text-gray-500">Professional credentials and expiry status.</p></div></div><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Certification</th><th class="p-3 text-left">Issuer</th><th class="p-3 text-left">Issued</th><th class="p-3 text-left">Expires</th><th class="p-3 text-left">Status</th><th class="p-3"></th></tr></thead><tbody>@forelse($staff->certifications as $certification)<tr class="border-t"><td class="p-3 font-medium">{{ $certification->cert_name }}</td><td class="p-3">{{ $certification->issuing_body }}</td><td class="p-3">{{ $certification->issue_date->format('d M Y') }}</td><td class="p-3">{{ $certification->expiry_date?->format('d M Y') ?? 'No expiry' }}</td><td class="p-3 capitalize">{{ $certification->status }}</td><td class="p-3 text-right">@can('update',$staff)<form method="POST" action="{{ route('web.staff.certifications.destroy',[$staff,$certification]) }}" onsubmit="return confirm('Remove this certification?');">@csrf @method('DELETE')<button class="text-red-600">Remove</button></form>@endcan</td></tr>@empty<tr><td colspan="6" class="p-6 text-center text-gray-500">No certifications recorded.</td></tr>@endforelse</tbody></table></div>@can('update',$staff)<form method="POST" action="{{ route('web.staff.certifications.store',$staff) }}" class="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-2 lg:grid-cols-5">@csrf<input name="cert_name" placeholder="Certification name" class="h-10 rounded-md border px-3 text-sm" required><input name="issuing_body" placeholder="Issuing body" class="h-10 rounded-md border px-3 text-sm" required><input type="date" name="issue_date" class="h-10 rounded-md border px-3 text-sm" required><input type="date" name="expiry_date" class="h-10 rounded-md border px-3 text-sm"><select name="status" class="h-10 rounded-md border px-3 text-sm"><option value="valid">Valid</option><option value="expired">Expired</option><option value="revoked">Revoked</option></select><button class="rounded-md bg-primary px-4 py-2 text-sm text-white sm:col-span-2 lg:col-span-1">Add certification</button></form>@endcan</section>
</div>
@endsection
