@extends('layouts.app') @section('title',$medicine->exists?'Edit medicine':'Add medicine') @section('content')
<div class="mx-auto max-w-3xl"><a href="{{ route('web.pharmacy.index') }}" class="text-sm text-primary">← Pharmacy</a><h1 class="my-4 text-2xl font-bold">{{ $medicine->exists?'Edit medicine':'Add medicine' }}</h1>
<form method="POST" action="{{ $medicine->exists?route('web.pharmacy.update',$medicine):route('web.pharmacy.store') }}" class="grid gap-4 rounded-lg border bg-background p-5 sm:grid-cols-2">@csrf @if($medicine->exists)@method('PUT')@endif
@foreach(['code'=>'Code','name'=>'Name','generic_name'=>'Generic name','category'=>'Category','manufacturer'=>'Manufacturer','barcode'=>'Barcode'] as $field=>$label)<label class="text-sm">{{ $label }}<input name="{{ $field }}" value="{{ old($field,$medicine->$field) }}" {{ in_array($field,['code','name'])?'required':'' }} class="mt-1 w-full rounded-md border px-3 py-2">@error($field)<span class="text-red-600">{{ $message }}</span>@enderror</label>@endforeach
<label class="text-sm">Type<select name="type" class="mt-1 w-full rounded-md border px-3 py-2">@foreach(['prescription','otc','controlled'] as $type)<option @selected(old('type',$medicine->type)===$type)>{{ $type }}</option>@endforeach</select></label>
<label class="text-sm">Selling price<input type="number" min="0" step="0.01" name="selling_price" value="{{ old('selling_price',$medicine->selling_price??0) }}" required class="mt-1 w-full rounded-md border px-3 py-2"></label>
<label class="text-sm">Currency<input name="currency" maxlength="3" value="{{ old('currency',$medicine->currency??'UGX') }}" required class="mt-1 w-full rounded-md border px-3 py-2"></label>
<label class="text-sm">Reorder level<input type="number" min="0" name="reorder_level" value="{{ old('reorder_level',$medicine->reorder_level??50) }}" required class="mt-1 w-full rounded-md border px-3 py-2"></label>
<div class="sm:col-span-2"><button class="rounded-md bg-primary px-4 py-2 text-white">Save medicine</button></div></form></div>@endsection
