<?php
namespace Tests\Feature\Web;
use App\Models\Company;use App\Models\Medicine;use App\Models\Patient;use App\Models\Staff;use App\Models\User;use Tests\TestCase;
class PharmacyManagementTest extends TestCase
{
 public function test_admin_creates_medicine_and_receives_batch_atomically():void{$company=$this->company();$user=User::factory()->create(['company_id'=>$company->id,'role'=>'admin']);$this->actingAs($user)->get(route('web.pharmacy.create'))->assertOk()->assertSee('Add medicine');$this->actingAs($user)->post(route('web.pharmacy.store'),['code'=>'MED-PH1','name'=>'Paracetamol','type'=>'otc','selling_price'=>500,'currency'=>'UGX','reorder_level'=>10])->assertRedirect();$medicine=Medicine::where('code','MED-PH1')->firstOrFail();$this->actingAs($user)->post(route('web.pharmacy.batches.store',$medicine),['batch_number'=>'LOT-1','expiry_date'=>today()->addYear()->toDateString(),'quantity'=>40,'reference'=>'GRN-1'])->assertRedirect();$this->actingAs($user)->get(route('web.pharmacy.show',$medicine))->assertOk()->assertSee('LOT-1')->assertSee('GRN-1');$this->assertSame(40,$medicine->fresh()->stock);$this->assertDatabaseHas('medicine_batches',['medicine_id'=>$medicine->id,'batch_number'=>'LOT-1','quantity'=>40]);$this->assertDatabaseHas('medicine_transactions',['medicine_id'=>$medicine->id,'type'=>'Received','quantity'=>40,'reference'=>'GRN-1']);}
 public function test_nurse_schedules_and_records_medication_administration_for_own_patient():void{$company=$this->company();$staff=Staff::create(['company_id'=>$company->id,'code'=>'N-PH','first_name'=>'Nurse','last_name'=>'One','email'=>'nurse.ph@example.test','phone'=>'+256700111111','role'=>'Nurse','status'=>'Active']);$user=User::factory()->create(['company_id'=>$company->id,'staff_id'=>$staff->id,'role'=>'nurse']);$patient=Patient::factory()->create(['company_id'=>$company->id]);$this->actingAs($user)->get(route('web.pharmacy.administrations'))->assertOk()->assertSee('Schedule');$this->actingAs($user)->post(route('web.pharmacy.administrations.store'),['patient_id'=>$patient->id,'medication'=>'Paracetamol','dosage'=>'500mg','scheduled_time'=>'09:30'])->assertRedirect();$row=$patient->medicationAdministrations()->firstOrFail();$this->actingAs($user)->patch(route('web.pharmacy.administrations.administer',$row))->assertRedirect();$this->assertSame('Administered',$row->fresh()->status);$this->assertSame($staff->id,$row->fresh()->administered_by);$this->assertNotNull($row->fresh()->administered_at);}
 public function test_templates_and_threshold_alerts_are_database_backed():void{$company=$this->company();$user=User::factory()->create(['company_id'=>$company->id,'role'=>'pharmacist']);Medicine::create(['code'=>'LOW-1','name'=>'Low medicine','stock'=>2,'reorder_level'=>5,'expiry'=>today()->addDays(10),'status'=>'In Stock']);$this->actingAs($user)->get(route('web.pharmacy.alerts'))->assertOk()->assertSee('Low medicine');$this->actingAs($user)->post(route('web.pharmacy.templates.store'),['name'=>'Malaria adult','category'=>'Infectious disease','medications'=>[['name'=>'Artemether','dosage'=>'80mg','frequency'=>'Twice daily','route'=>'Oral']]])->assertRedirect();$this->assertDatabaseHas('medicine_templates',['company_id'=>$company->id,'name'=>'Malaria adult']);$this->actingAs($user)->get(route('web.pharmacy.templates'))->assertOk()->assertSee('Malaria adult')->assertSee('Artemether');}
 public function test_legacy_pharmacy_pages_redirect_to_native_routes():void{$company=$this->company();$user=User::factory()->create(['company_id'=>$company->id,'role'=>'admin']);foreach(['medicine'=>'web.pharmacy.index','add-medicine'=>'web.pharmacy.create','stock-alerts'=>'web.pharmacy.alerts','medicine-templates'=>'web.pharmacy.templates'] as $page=>$route){$this->actingAs($user)->get("/{$page}.html")->assertRedirect(route($route));}}
 private function company():Company{return Company::create(['code'=>'PH-'.str()->random(5),'name'=>'Pharmacy Hospital','email'=>str()->random(5).'@example.test','contact_person'=>'Admin','phone'=>'+256700000001','city'=>'Kampala']);}
}
